esphome:
  name: epaper_portrait
  platform: ESP32
  board: esp32dev

ota:

api:

logger:

wifi:
  ssid: !secret wifissid
  password: !secret wifipass
  fast_connect: true
  manual_ip:
    static_ip: 192.168.20.45
    gateway: 192.168.20.1
    subnet: 255.255.255.0

spi:
  clk_pin: 18
  mosi_pin: 23

time:
  - platform: homeassistant
    id: esptime

font:
  - file: "lovebeat.ttf"
    id: midfont
    size: 30
  - file: "lovebeat.ttf"
    id: bigfont
    size: 40
  - file: "lovebeat.ttf"
    id: smallfont
    size: 15
  - file: "monofonto.ttf"
    id: smallbebas
    size: 16
  - file: "monofonto.ttf"
    id: verysmallbebas
    size: 12


sensor:
  - platform: homeassistant
    id: sauna_temperature
    internal: true
    entity_id: sensor.sauna
  - platform: homeassistant
    id: ulko_temperature
    entity_id: sensor.ulko
    internal: true
  - platform: homeassistant
    id: terassi_temperature
    entity_id: sensor.terassi
    internal: true
  - platform: homeassistant
    id: autotalli_temperature
    entity_id: sensor.ulkovalot_sauna_si7021_temperature
    internal: true
  - platform: homeassistant
    id: saunatupa_temperature
    entity_id: sensor.saunatupa
    internal: true
  - platform: homeassistant
    id: uv_now
    internal: true
    entity_id: sensor.uv_now
  - platform: homeassistant
    id: water_daily_litres
    internal: true
    entity_id: sensor.daily_water_in_litres

text_sensor:
  - platform: homeassistant
    id: etuovi
    entity_id: lock.lohko
    internal: true
  - platform: homeassistant
    id: takaovi
    entity_id: lock.takaovi
    internal: true
  - platform: homeassistant
    id: saunatupa
    entity_id: lock.saunatupa
    internal: true

image:
  - file: "penguin.png"
    id: penguin
  - file: "penguin_scarf.png"
    id: penguinscarf
  - file: "penguin_blehat.png"
    id: penguinblehat
  - file: "lock_open.png"
    id: lockopen
  - file: "lock_closed.png"
    id: lockclosed

display:
  - platform: waveshare_epaper
    cs_pin: 5
    dc_pin: 19
    busy_pin: 4
    reset_pin: 12
    model: 2.90in
    rotation: 180°
    full_update_every: 300
    update_interval: 2s
    lambda: |-
         
         it.strftime(64, 2, id(bigfont), TextAlign::TOP_CENTER, "%H:%M", id(esptime).now());
         it.line(0, 42, 300, 42);
         it.printf(64, 148, id(bigfont), TextAlign::TOP_CENTER, "%.1fC", id(ulko_temperature).state);

         
         if (id(ulko_temperature).state<0) {
           it.image(15, 50, id(penguinscarf)); 
         } else {
           it.image(15, 50, id(penguin));
         }
         if (id(ulko_temperature).state>20) {
           it.image(15, 50, id(penguinblehat)); 
           it.printf(0, 42, id(smallbebas), TextAlign::TOP_LEFT, "UV%.0f", id(uv_now).state);
         } else {
           it.image(15, 50, id(penguin));
         }
         it.printf(125, 42, id(smallbebas), TextAlign::TOP_RIGHT, "%.0fL", id(water_daily_litres).state);

         it.printf(12, 185, id(smallbebas), TextAlign::TOP_LEFT, "E");
         it.printf(50, 185, id(smallbebas), TextAlign::TOP_LEFT, "T");
         it.printf(90, 185, id(smallbebas), TextAlign::TOP_LEFT, "S");
         if (id(etuovi).state == "locked") {
           it.image(17, 185, id(lockclosed));
         } else {
           it.image(17, 185, id(lockopen));
         }
         
         
         if (id(takaovi).state == "locked") {
           it.image(57, 185, id(lockclosed));
         } else {
           it.image(57, 185, id(lockopen));
         }
         
         
         if (id(saunatupa).state == "locked") {
           it.image(97, 185, id(lockclosed));
         } else {
           it.image(97, 185, id(lockopen));
         }
         

         it.line(0, 208, 300, 208);
         it.printf(0, 210, id(smallbebas), TextAlign::TOP_LEFT, "SAUNATUPA");
         it.printf(125, 210, id(smallbebas), TextAlign::TOP_RIGHT, "%.1f°C", id(saunatupa_temperature).state);

         it.printf(0, 230, id(smallbebas), TextAlign::TOP_LEFT, "AUTOTALLI");
         it.printf(125, 230, id(smallbebas), TextAlign::TOP_RIGHT, "%.1f°C", id(autotalli_temperature).state);

         it.printf(0, 250, id(smallbebas), TextAlign::TOP_LEFT, "TERASSI");
         it.printf(125, 250, id(smallbebas), TextAlign::TOP_RIGHT, "%.1f°C", id(terassi_temperature).state);

         it.printf(0, 270, id(smallbebas), TextAlign::TOP_LEFT, "SAUNA");
         it.printf(125, 270, id(smallbebas), TextAlign::TOP_RIGHT, "%.1f°C", id(sauna_temperature).state);
