esphome:
  name: h801_office

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifissid
  password: !secret wifipass
  fast_connect: true
  manual_ip:
    static_ip: 192.168.20.62
    gateway: 192.168.20.1
    subnet: 255.255.255.0

logger:
api:
ota:

# R 	GPIO15
# G 	GPIO13
# B 	GPIO12
# W1 	GPIO14
# W2 	GPIO04
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_w

light:
  - platform: monochromatic
    output: pwm_w
    name: "Office letku"
