esphome:
  name: saunaled

esp8266:
  board: esp01_1m

logger:
api:
ota:


wifi:
  ssid: !secret wifissid
  password: !secret wifipass
  fast_connect: true
  power_save_mode: HIGH
  manual_ip:
    static_ip: 192.168.20.51
    gateway: 192.168.20.1
    subnet: 255.255.255.0


output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w
light:
  - platform: rgbw
    name: "saunaled"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w