esphome:
  name: refri_fan
  platform: ESP32
  board: esp32dev

ota:

api:

logger:

web_server:
  port: 80

wifi:
  # ssid: !secret wifissid
  # password: !secret wifipass
  fast_connect: true
  power_save_mode: HIGH
  manual_ip:
    static_ip: 192.168.8.61
    gateway: 192.168.8.1
    subnet: 255.255.255.0

output:
  - platform: ledc
    id: output_1
    pin: GPIO4
    frequency: "25000 Hz"

fan:
  - platform: speed
    output: output_1
    name: "Refridgerator fan"
